// <auto-generated />
// Do not modify this file manually.
namespace ExcelAddIn
{
  partial class ThisAddIn
  {
    #region VSTO generated code

    /// <summary>
    /// Required by VSTO — wires Startup/Shutdown events.
    /// </summary>
    private void InternalStartup()
    {
      this.Startup += new System.EventHandler(ThisAddIn_Startup);
      this.Shutdown += new System.EventHandler(ThisAddIn_Shutdown);
    }

    #endregion
  }
}
